### ISSUE TITLE
unknown_command_spec.rb tests from latest master seems to clash with RSMP core specification.

### ISSUE THREAD

**Issue by sveitech** [rsmp-nordic/rsmp_validator#271] opened 2023-05-24 13:19 UTC
Specification: https://rsmp-nordic.org/rsmp_specifications/core/3.2/applicability/basic_structure.html#command-messages

> If the object is not known then the site must not disconnect but instead answer with this type of message where age is set to undefined.

The first test in the spec file, "sending an invalid command request", expects MessageNotAck, but from the specification it seems like the proper response is a CommandResponse with age=undefined.

So, do you mean that:

If "cCI" is KNOWN, but "n" is unknown, is should result in CommandResponse with age = undefined, and
if "cCI" is UNKNOWN it should result in MessageNotAck ?

It seems confusing. Perhaps a streamlining of expected error reporting would be in order? Always use MessageNotAck for errors?

**Comment by emiltin** [comment] 2023-05-25 06:35
issue in core: https://github.com/rsmp-nordic/rsmp_core/issues/107

**Comment by emiltin** [comment] 2023-05-25 06:36
issue in core repo: https://github.com/rsmp-nordic/rsmp_core/issues/107

**Comment by emiltin** [comment] 2023-06-19 11:42
I agree it does not seem very clear from the spec. @otterdahl can you help here? what's the correct way for a site to respond to an inknown command, and where in the spec is it defined?

**Comment by otterdahl** [comment] 2023-06-22 12:29
> > If the object is not known then the site must not disconnect but instead answer with this type of message where age is set to undefined.

> The first test in the spec file, "sending an invalid command request", expects MessageNotAck, but from the specification it seems like the proper response is a CommandResponse with age=undefined.

The spec refers to the object (or component, `cId`). If `cId` is unknown, then the TLC should respond with age=`undefined`. 
The test case however, has an non-exsistant command code `cCI`, M0000. In that case it should answer with an MessageNotAck.

> If "cCI" is KNOWN, but "n" is unknown, is should result in CommandResponse with age = undefined, and if "cCI" is UNKNOWN it should result in MessageNotAck ?

Both `cCI` and `n` are defined in the SXL (as part of commands) and if there is a mismatch then it should result in MessageNotAck.  An error of this kind could be due to SXL mismatch and it is questionable if the communicaton can or even should continue.

However, a missmatch of the component (`cId`), such as the signal groups and detector logics is a different story. This error could be the result in a configuration problem, e.g the number of signal groups and detector logic defined. This type of error is not considered quite as serious (unless it refers to the cId of the TLC itself) and sending a reply with age=`undefined` is enough rather terminating the entire communication (like some implementations did). We added this in RSMP 3.1.3 because we learned that this issue was more common than we expected.

To summerize:

Type of mismatch | Expected result
-|-
`cId` | age=undefined
`cCI` | MessageNotAck
`n` | MessageNotAck

> I agree it does not seem very clear from the spec. @otterdahl can you help here? what's the correct way for a site to respond to an inknown command, and where in the spec is it defined?

It is defined in the [Message acknowledment](https://rsmp-nordic.github.io/rsmp_specifications/core/3.2.1/applicability/basic_structure.html#message-acknowledgement) section, but not very clearly. But we have added this to the [faq ](https://github.com/rsmp-nordic/rsmp_core/blob/master/faq.md#commandresponse-and-messageack) years ago, but that hasn't made itself completly into the specification yet.

**Comment by emiltin** [comment] 2023-07-07 11:29
i'm updating the validator tests to reflect the behaviour described above.

But what does it mean to set age=undefined? A command response contains multiple age attributes inside rvs:

```json
"rvs":[
  {"cCI":"M0001","n":"securityCode","v":"2222","age":"recent"}
  {"cCI":"M0001","n":"status","v":"NormalControl","age":"recent"},
  {"cCI":"M0001","n":"timeout","v":"0","age":"recent"},
  {"cCI":"M0001","n":"intersection","v":"0","age":"recent"}
]
```

Which ones whould be set to what?

**Comment by otterdahl** [comment] 2023-07-07 14:04
Since all of the return values /`rvs`) in your example is related to the same `cId`, they all need to be `age: undefined`.

**Comment by emiltin** [comment] 2023-07-13 08:41
if age=undefined, what should v be set to?
for status reponses, the spec states that s must be set to null, see https://rsmp-nordic.github.io/rsmp_specifications/core/3.2/applicability/basic_structure.html?highlight=null#return-values-returnvalue. but i did not find a similar requirement for command responses?

**Comment by emiltin** [comment] 2023-07-14 09:53
with #334, the validator expects age=undefined if we send a command with an non-existing component id. closing this issue as I think the expected behaviour has been clarified and is reflected int he validator.

discussion about error streamlining is in e.g https://github.com/rsmp-nordic/rsmp_core/issues/107

**Closed by emiltin** 2023-07-14 09:53 UTC
Labels: question
